# Generated by Django 5.1.15 on 2026-05-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_company_vehicle_fitness_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='puc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/puc/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
