# Generated by Django 5.1.15 on 2026-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_company_alert_expiring_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appearance_mode',
            field=models.CharField(default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_language',
            field=models.CharField(default='English (India)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
