# Generated by Django 5.1.15 on 2026-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_trip_fuel_cost_trip_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
