# Generated by Django 5.1.15 on 2026-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_alter_trip_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('lgv_lmv', 'Light Goods Vehicle (LGV/LMV - Gross Weight <7.5T)'), ('mhcv', 'Medium Heavy Commercial Vehicle (MHCV)'), ('torus', 'Torus (Tipper)'), ('multi_axle', 'Multi-Axle Truck'), ('trailer', 'Trailer with Loading Capacity')], default='lgv_lmv', max_length=50),
        ),
    ]
