# Generated by Django 5.1.15 on 2026-05-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_vehicle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='category',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='loading_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Loading capacity in metric tons', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('lmv', 'Light Goods Vehicle / LMV (Gross Weight < 7.5 Ton)'), ('mhv', 'Medium Heavy Vehicle'), ('torus', 'Torus'), ('multi_axle', 'Multi-Axle Truck'), ('trailer', 'Trailer')], default='lmv', max_length=30),
        ),
    ]
