# Generated by Django 5.1.15 on 2026-05-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_remove_vehicle_category_vehicle_loading_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='loading_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in tons', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('lmv', 'Light Goods Vehicle / LMV (< 7.5t)'), ('mhv', 'Medium Heavy Vehicle'), ('torus', 'Torus'), ('multi_axle', 'Multi Axle Truck'), ('trailer', 'Trailer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
