# Generated by Django 5.1.15 on 2026-05-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_alter_vehicle_loading_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='badge_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dl_back',
            field=models.FileField(blank=True, null=True, upload_to='documents/driver/dl/'),
        ),
        migrations.AddField(
            model_name='user',
            name='dl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dl_front',
            field=models.FileField(blank=True, null=True, upload_to='documents/driver/dl/'),
        ),
        migrations.AddField(
            model_name='user',
            name='hazmat_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_type',
            field=models.CharField(blank=True, choices=[('LMV', 'Light Motor Vehicle (LMV)'), ('HMV', 'Heavy Motor Vehicle (HMV)'), ('Trailer', 'HPMV/HGMV with Trailer Endorsement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/driver/medical/'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='police_verification',
            field=models.FileField(blank=True, null=True, upload_to='documents/driver/police/'),
        ),
        migrations.AddField(
            model_name='user',
            name='police_verification_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
