# Generated by Django 5.1.15 on 2026-05-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_user_aadhaar_number_user_badge_number_user_dl_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_speed',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Speed in km/h', max_digits=6),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
