# Generated by Django 5.1.15 on 2026-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_vehicle_current_latitude_vehicle_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
