# Generated by Django 5.1.15 on 2026-05-09 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_user_requires_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('volume_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_at_fill', models.IntegerField(help_text='Odometer reading at the time of filling (km)')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/fuel_entries/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='fleet.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fuel_entries', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='fleet.trip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
