# Generated by Django 5.1.15 on 2026-05-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_fuel_entry_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trip completion bonus awarded by manager (INR)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly base salary (INR) — set by manager', max_digits=10, null=True),
        ),
    ]
