# Generated by Django 5.1.15 on 2026-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_driver_salary_trip_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_distance_km',
            field=models.PositiveIntegerField(blank=True, help_text='Planned route distance in kilometres', null=True),
        ),
    ]
