# Generated by Django 5.1.15 on 2026-05-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_add_total_distance_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Breakdown Repair'), ('tyre', 'Tyre Replacement'), ('oil', 'Oil Change'), ('brake', 'Brake Service'), ('electrical', 'Electrical Repair'), ('bodywork', 'Bodywork / Denting'), ('other', 'Other')], default='routine', max_length=20)),
                ('description', models.TextField()),
                ('garage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer_at_service', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, help_text='Recommended next service date', null=True)),
                ('invoice_image', models.ImageField(blank=True, null=True, upload_to='maintenance/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.company')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
