# Generated by Django 5.1.15 on 2026-05-09 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_maintenance_record_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_life',
            field=models.PositiveSmallIntegerField(default=54, help_text='Battery score 0-100'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_heading',
            field=models.CharField(blank=True, help_text='e.g. North-East', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_compression',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='PSI', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_performance',
            field=models.PositiveSmallIntegerField(default=92, help_text='Engine score 0-100'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_integrity',
            field=models.PositiveSmallIntegerField(default=96, help_text='Tyre score 0-100'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_pressure',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Bar', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(help_text='e.g. Engine Tune-up, Tire Rotation', max_length=100)),
                ('last_service_date', models.DateField()),
                ('next_scheduled_check', models.DateField()),
                ('technician', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming'), ('OVERDUE', 'Overdue')], default='UPCOMING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-last_service_date'],
            },
        ),
    ]
