# Generated by Django 5.1.15 on 2026-05-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_vehicle_health_and_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLoadPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_type', models.CharField(max_length=100)),
                ('weight_tons', models.DecimalField(decimal_places=2, max_digits=5)),
                ('required_vehicle_type', models.CharField(max_length=50)),
                ('origin_lat', models.FloatField()),
                ('origin_lon', models.FloatField()),
                ('destination_lat', models.FloatField()),
                ('destination_lon', models.FloatField()),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Internal Only'), ('PUBLIC', 'All Tenants'), ('PARTNER', 'Trusted Only')], default='PRIVATE', max_length=10)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('origin_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_loads', to='fleet.company')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_estimated_fuel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('outbound_trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_leg_binding', to='fleet.trip')),
                ('return_trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_leg_binding', to='fleet.trip')),
            ],
        ),
    ]
