# Generated by Django 5.1.15 on 2026-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_globalloadpool_linkedtrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Standard Rate (%)', max_digits=5)),
                ('heavy_asset_commission_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Heavy Asset Rate (%)', max_digits=5)),
                ('flat_transaction_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat Fee per Transaction', max_digits=10)),
                ('enable_cross_tenant_matching', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.AddField(
            model_name='linkedtrip',
            name='settlement_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
