# Generated by Django 5.1.15 on 2026-05-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_globalsettings_linkedtrip_settlement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/photos/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('doc_expiry', 'Document Expiry'), ('maintenance', 'Maintenance Request'), ('trip_assigned', 'Trip Assigned'), ('fuel_approval', 'Fuel Bill Approval'), ('panic', 'Emergency / SOS'), ('fault_report', 'Vehicle Fault Report')], max_length=30),
        ),
    ]
