# Generated by Django 5.1.15 on 2026-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_add_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager_performance_notes',
            field=models.TextField(blank=True, help_text='Manager evaluation notes', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manager_performance_score',
            field=models.IntegerField(blank=True, help_text='Manager evaluation score (0-100)', null=True),
        ),
    ]
