# Generated by Django 5.1.15 on 2026-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_user_manager_performance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager_efficiency_score',
            field=models.IntegerField(blank=True, help_text='Manager efficiency score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manager_punctuality_score',
            field=models.IntegerField(blank=True, help_text='Manager punctuality score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manager_safety_score',
            field=models.IntegerField(blank=True, help_text='Manager safety score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager_performance_score',
            field=models.IntegerField(blank=True, help_text='Manager overall evaluation score (0-100)', null=True),
        ),
    ]
