# Generated by Django 5.1.15 on 2026-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_user_manager_efficiency_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalloadpool',
            name='destination_name',
            field=models.CharField(blank=True, help_text='Human-readable destination name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalloadpool',
            name='origin_name',
            field=models.CharField(blank=True, help_text='Human-readable origin name', max_length=255, null=True),
        ),
    ]
