# Generated by Django 5.1.15 on 2026-05-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_user_date_of_birth_user_driving_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alert_expiring_docs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='alert_fuel_approvals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='alert_maintenance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='alert_trip_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='doc_expiry_lead_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
