# Generated by Django 5.1.15 on 2026-05-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_user_appearance_mode_user_platform_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pre_trip_check',
            field=models.BooleanField(default=False),
        ),
    ]
