# Generated by Django 5.1.15 on 2026-05-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_trip_pre_trip_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
