# Generated by Django 5.1.15 on 2026-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='goods_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='goods_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
